# Where to plot and log
directories:
        # One directory for logs
        log: /home/chia/chia/logs

        # One or more directories; the scheduler will use all of them
        tmp:
                - /mnt/tmp/00
                - /mnt/tmp/01
                - /mnt/tmp/02
                - /mnt/tmp/03
                - /mnt/tmp/04
                - /mnt/tmp/05
                - /mnt/tmp/06
                - /mnt/tmp/07
                - /mnt/tmp/08
                - /mnt/tmp/09
                - /mnt/tmp/10
                - /mnt/tmp/11

        # One directory (TODO: support distributing across multiple tmp2 dirs)
        tmp2: /mnt/tmp/a

        # One or more directories; the scheduler will use all of them 
        dst:
                - /home/chia/chia/plots/000
                - /home/chia/chia/plots/001
                - /home/chia/chia/plots/002
                - /home/chia/chia/plots/003

        # Archival
        archive:
                rsyncd_module: plots
                rsyncd_path: /plots
                rsyncd_bwlimit: 100000  # In KB/s
                rsyncd_host: farmer
                rsyncd_user: chia


# Plotting scheduling parameters
scheduling:
        # Don't run a job on a particular temp dir more often than this.
        # (obsolete)
        # tmpdir_stagger_m: 300
        tmpdir_stagger_phase_major: 2
        tmpdir_stagger_phase_minor: 5
        tmpdir_max_jobs: 3

        # Global min; don't run any jobs more often than this.
        global_stagger_m: 30

        # How often the daemon wakes to consider starting a new plot job
        polling_time_s: 20

# Plotting parameters
plotting:
        k: 32
        n_threads: 8         # Threads per job
        # n_buckets: 64        # Number of buckets to split data into
        # job_buffer: 9200     # Per job memory
        n_buckets: 128       # Number of buckets to split data into
        job_buffer: 4580     # Per job memory
